# Some global variables that are useful to reference


TV_MODEL_LIST = [
    'resnet18',
    'alexnet',
    'squeezenet1_0',
    'vgg16',
    'densenet161',
    'inception_v3',
    'googlenet',
    'shufflenet_v2_x1_0',
    'mobilenet_v2',
    'mobilenet_v3_small',
    'mobilenet_v3_large',
    'resnext50_32x4d',
    'wide_resnet50_2',
    'mnasnet1_0',
    'efficientnet_b0',
    'efficientnet_b1',
    'efficientnet_b2',
    'efficientnet_b3',
    'efficientnet_b4',
    'efficientnet_b5',
    'efficientnet_b6',
    'efficientnet_b6',
    'efficientnet_b7',
    'regnet_y_400mf',
    'regnet_y_800mf',
    'regnet_y_1_6gf',
    'regnet_y_3_2gf',
    'regnet_y_8gf',
    'regnet_y_16gf',
    'regnet_y_32gf',
    'regnet_x_400mf',
    'regnet_x_800mf',
    'regnet_x_1_6gf',
    'regnet_x_3_2gf',
    'regnet_x_8gf',
    'regnet_x_16gf',
    'regnet_x_32gf',
]